// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ⚠️  STUB FILE — Replace this with the real file generated by:
//     flutterfire configure
//
// Until you run `flutterfire configure` and link a real Firebase project,
// the app will crash at runtime with a [Firebase] error. This stub exists
// only to allow the project to compile.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── STUB VALUES ─────────────────────────────────────────────────────────────
  // Replace all values below with real ones from your Firebase console
  // or run: flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE-WITH-REAL-API-KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'REPLACE-WITH-REAL-PROJECT-ID',
    authDomain: 'REPLACE-WITH-REAL-PROJECT-ID.firebaseapp.com',
    storageBucket: 'REPLACE-WITH-REAL-PROJECT-ID.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmgbsm5pxNNqAxpn7AOGtKocw9HM0jZbo',
    appId: '1:41188065744:android:d6be72601f99be0b9239d5',
    messagingSenderId: '41188065744',
    projectId: 'janvekar-family-tree',
    storageBucket: 'janvekar-family-tree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nPrR0BgSKWElNU9Jd-lzmhD_7sOR3jw',
    appId: '1:41188065744:ios:88c0e4885f34d6849239d5',
    messagingSenderId: '41188065744',
    projectId: 'janvekar-family-tree',
    storageBucket: 'janvekar-family-tree.firebasestorage.app',
    iosBundleId: 'com.janvekar.genealogyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE-WITH-REAL-API-KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'REPLACE-WITH-REAL-PROJECT-ID',
    storageBucket: 'REPLACE-WITH-REAL-PROJECT-ID.firebasestorage.app',
    iosBundleId: 'com.janvekar.genealogyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE-WITH-REAL-API-KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'REPLACE-WITH-REAL-PROJECT-ID',
    storageBucket: 'REPLACE-WITH-REAL-PROJECT-ID.firebasestorage.app',
    authDomain: 'REPLACE-WITH-REAL-PROJECT-ID.firebaseapp.com',
  );
}